# Site settings
title: Roland Kwitt
description: > # this means to ignore newlines until "baseurl:"
  Associate Professor  
  Department of Computer Science  
  University of Salzburg
  
email: roland.kwitt@gmail.com

theme: jekyll-theme-minimal
