# Site settings
title: Roland Kwitt
description: <p><b>Full Professor</b><br>Department of Artificial Intelligence and Human Interfaces<br>University of Salzburg<br><a href="https://github.com/rkwitt" target="_blank">
    <i class="fa-brands fa-github"></i> </a> <a href="https://x.com/rkwitt1982/" target="_blank" aria-label="Twitter">
    <i class="fa-brands fa-twitter"></i>
  </a>
  <a href="https://orcid.org/0000-0001-9947-4465" target="_blank" aria-label="ORCID">
      <i class="ai ai-orcid"></i>
    </a>
  <a href="https://bsky.app/profile/rkwitt.bsky.social" target="_blank" aria-label="Bluesky">
      <i class="fa-brands fa-bluesky"></i>
    </a>
  <a href="https://dblp.org/pid/60/4140.html" target="_blank" aria-label="DBLP" style="color: inherit;">
    <img src="/assets/icons/dblp.svg" alt="DBLP" style="width:20px; height:20px; vertical-align:middle;">
  </a>
  </p>
email: roland.kwitt@gmail.com
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from